require "test.utils"

dofile("test/packed.lua")
dofile("test/embedded.lua")
dofile("test/dynamic.lua")
dofile("test/empty.lua")
dofile("test/bool.lua")
dofile("test/number.lua")
dofile("test/bitnumbers.lua")
dofile("test/text.lua")
dofile("test/standard.lua")
dofile("test/array.lua")
dofile("test/list.lua")
dofile("test/set.lua")
dofile("test/map.lua")
dofile("test/union.lua")
dofile("test/tuple.lua")
dofile("test/flatbuffermonster.lua")
dofile("test/typeref.lua")
dofile("test/type.lua")