dofile("tests/dynamictests.lua")
dofile("tests/encodingtests.lua")
dofile("tests/monsterexampletest.lua")
dofile("tests/objecttests.lua")
dofile("tests/primitivetests.lua")
dofile("tests/standardtests.lua")
dofile("tests/typreftests.lua")